import React from 'react';
import BannerSlider from './BannerSlider';
import MapSection from './MapSection';
import Footer from './Footer';
import Navbar from './Navbar';
import emp from '../assets/employee.png';
import esm from '../assets/ESM.png';
import announcement from '../assets/announcement.png';
import rti from '../assets/RTI.png';
import tender from '../assets/tenders.png';
import mediclaim from '../assets/mediclaim.png';
import color from '../assets/color.jpg';
import bandw from '../assets/bandw.jpg';
import thermal from '../assets/thermal.png';
import hydro from '../assets/hydro.png';
import solar from '../assets/solar.png';
import gas from '../assets/gas.png';
import bgvideo from '../assets/bgvideo.mp4'; // Import the background video

const Header = () => {
  return (
    <header className="relative w-full">
      {/* Background video */}
      <video
        className="absolute top-0 left-0 object-cover w-full h-screen"
        style={{ zIndex: 1 }}
        autoPlay
        loop
        muted
      >
        <source src={bgvideo} type="video/mp4" />
        Your browser does not support the video tag.
      </video>

      {/* Navbar */}
      <Navbar />

      {/* Section Below Navbar */}
      <section className="relative flex justify-center items-center bg-white mt-[80vh]" style={{ zIndex: 20 }}>
        <div className="grid grid-cols-6 gap-20 px-8 md:px-16">
          <div className="flex flex-col items-center justify-center mb-4 shadow-2xl h-35 w-35 rounded-xl">
            <img src={emp} alt="" className="mb-2" />
            <p className="text-center">Employee</p>
          </div>
          <div className="flex flex-col items-center justify-center mb-4 shadow-2xl h-35 w-35 rounded-xl">
            <img src={esm} alt="" className="mb-2" />
            <p className="text-center">ESM</p>
          </div>
          <div className="flex flex-col items-center justify-center mb-4 shadow-2xl h-35 w-35 rounded-xl">
            <img src={announcement} alt="" className="mb-2" />
            <p className="text-center">Announcements</p>
          </div>
          <div className="flex flex-col items-center justify-center mb-4 shadow-2xl h-35 w-35 rounded-xl">
            <img src={rti} alt="" className="mb-2" />
            <p className="text-center">RTI</p>
          </div>
          <div className="flex flex-col items-center justify-center mb-4 shadow-2xl h-35 w-35 rounded-xl">
            <img src={tender} alt="" className="mb-2" />
            <p className="text-center">Tenders</p>
          </div>
          <div className="flex flex-col items-center justify-center mb-4 shadow-2xl h-35 w-35 rounded-xl">
            <img src={mediclaim} alt="" className="mb-2" />
            <p className="text-center">Mediclaim</p>
          </div>
        </div>
      </section>

      <section className="relative flex justify-center items-center bg-white mt-[5vh] px-8 md:px-16" style={{ zIndex: 20 }}>
        <div className="grid grid-cols-1 gap-8 p-8 m-10 md:grid-cols-2">
          <div className="flex flex-col items-start">
            <h2 className="mb-4 text-4xl font-bold text-blue-900">WELCOME TO MAHAGENCO</h2>
            <p className="mb-4 text-lg text-gray-600">
              The Mahanirmitee or Mahagenco (Maharashtra State Power Generation Company Limited - MSPGCL)
              formerly known as MSEB (Maharashtra State Electricity Board) is a major power generating company
              in the state of Maharashtra, India and a wholly owned subsidiary of Maharashtra State Electricity Board.
            </p>
            <p className="mb-4 text-lg text-gray-600">
              With a total generation of 13880.55 MW, it is the largest power producing company in India controlled
              by state government. The power generated by Mahagenco is supplied to Maharashtra. It was a part of Maharashtra
              State Electricity Board until 6 June 2005.
            </p>
            <div className="border-[#0097D8] border-2 w-30 text-center h-8 align-middle">
              <div>
                <button className="text-blue-500 hover:underline">Explore more</button>
              </div>
            </div>
          </div>
          <div className="flex items-center justify-center space-x-4 translate-x-10">
            <div className="flex-shrink-0">
              <img
                src={color}
                alt="Image 1"
                className="absolute object-cover rounded-lg shadow-md w-90 h-110 translate-y-[-90px] translate-x-[-130px]"
              />
            </div>
            <div className="absolute left-0 top-20">
              <p>STARTED IN</p>
              <p className="text-6xl">1960</p>
            </div>
            <div className="flex-shrink-0">
              <img
                src={bandw}
                alt="Image 2"
                className="object-cover w-full h-full rounded-lg shadow-md"
              />
            </div>
          </div>
        </div>
      </section>

      <section className="py-10 mt-20 ml-45 mr-45 bg-[#BFE5FD] rounded-3xl border-2 border-[#0097D8]" style={{ zIndex: 20 }}>
        <div className="flex-col justify-center max-w-screen-xl px-6 mx-auto">
          <h2 className="text-xl font-semibold text-center text-white rounded-[30px] bg-[#0097D8] p-2 pl-5 pr-5 w-max mx-auto translate-y-[-65px]">
            Power Generation Capacity In MW
          </h2>
          <div className="grid grid-cols-2 gap-8 sm:grid-cols-4 h-35 translate-y-[-20px]">
            {/* Thermal */}
            <div className="flex flex-col items-center px-6 py-4 bg-[#BFE5FD] rounded-xl">
              <img src={thermal} alt="Thermal" className="mb-2 h-15 w-15" />
              <p className="text-5xl font-semibold text-[#181B31]">10200</p>
              <p className="text-2xl text-[#181B31]">Thermal</p>
            </div>
            {/* Hydro */}
            <div className="flex flex-col items-center px-6 py-4 bg-[#BFE5FD] rounded-xl">
              <img src={hydro} alt="Hydro" className="w-12 h-12 mb-4" />
              <p className="text-5xl font-semibold text-[#181B31]">2580</p>
              <p className="text-2xl text-[#181B31]">Hydro</p>
            </div>
            {/* Solar */}
            <div className="flex flex-col items-center px-6 py-4 bg-[#BFE5FD] rounded-xl">
              <img src={solar} alt="Solar" className="w-12 h-12 mb-4" />
              <p className="text-5xl font-semibold text-[#181B31]">428</p>
              <p className="text-2xl text-[#181B31]">Solar</p>
            </div>
            {/* Gas */}
            <div className="flex flex-col items-center px-6 py-4 bg-[#BFE5FD] rounded-xl">
              <img src={gas} alt="Gas" className="w-12 h-12 mb-4" />
              <p className="text-5xl font-semibold text-[#181B31]">672</p>
              <p className="text-2xl text-[#181B31]">Gas</p>
            </div>
          </div>
        </div>
      </section>

      <BannerSlider />
      <MapSection />
      <Footer />
    </header>
  );
};

export default Header;
